-- THE MINIMUM SCHEMA `put_on_table` TOUCHES — for the test cluster, nothing else.
--
-- WHY THIS EXISTS RATHER THAN REPLAYING supabase/migrations. That directory is
-- the whole product: markets, events, positions, DNA caches, a hundred policies
-- and a dozen extensions. Replaying it to test one function would mean the test
-- fails whenever anything anywhere else does, which is the opposite of a useful
-- signal.
--
-- WHAT IT MUST NOT DO IS DIVERGE. Every constraint below is copied from the
-- migration that owns it, and the ones that matter are exactly the ones the
-- function collides with on purpose:
--
--   challenges_active_slot_idx     the cap, enforced by the database
--   challenges_active_market_idx   one market cannot consume two slots
--   market_calls PK                unique FOREVER, not per Challenge
--   market_calls_relation          the six-value CHECK, the current blocker
--   market_calls_not_self          your conviction cannot ask you
--
-- `challenge_integrity.test.ts` asserts these against the real migration files,
-- so a constraint that changes there and not here fails the suite rather than
-- quietly making the tests weaker than production.

CREATE TABLE public.challenges (
  id                bigserial   PRIMARY KEY,
  challenger_wallet text        NOT NULL,
  market_id         bigint      NOT NULL,
  slot_no           smallint    NOT NULL CHECK (slot_no BETWEEN 1 AND 3),
  created_at        timestamptz NOT NULL DEFAULT now(),
  closed_at         timestamptz,
  close_reason      text        CHECK (close_reason IN ('creator', 'all_responded')),
  parent_call       bigint
);

CREATE UNIQUE INDEX challenges_active_slot_idx
  ON public.challenges (challenger_wallet, slot_no) WHERE closed_at IS NULL;
CREATE UNIQUE INDEX challenges_active_market_idx
  ON public.challenges (challenger_wallet, market_id) WHERE closed_at IS NULL;

CREATE TABLE public.market_calls (
  market_id        bigint      NOT NULL,
  caller_wallet    text        NOT NULL,
  responder_wallet text        NOT NULL,
  relation_at_call text        NOT NULL,
  called_at        timestamptz NOT NULL DEFAULT now(),
  responded_at     timestamptz,
  passed_at        timestamptz,
  challenge_id     bigint      REFERENCES public.challenges(id),
  id               bigint      GENERATED BY DEFAULT AS IDENTITY,
  responded_side   text        CHECK (responded_side IS NULL OR responded_side IN ('YES', 'NO')),
  PRIMARY KEY (market_id, caller_wallet, responder_wallet),
  CONSTRAINT market_calls_not_self CHECK (caller_wallet <> responder_wallet),
  CONSTRAINT market_calls_relation CHECK (
    relation_at_call IN ('twin', 'tribe', 'opp', 'inverse', 'neutral', 'insufficient')
  )
);

CREATE UNIQUE INDEX market_calls_id_idx ON public.market_calls (id);

ALTER TABLE public.challenges
  ADD CONSTRAINT challenges_parent_call_fkey
  FOREIGN KEY (parent_call) REFERENCES public.market_calls(id);
