-- THE MINIMUM SCHEMA THE SIMULATION MIGRATION LANDS ON — for the test cluster.
--
-- Same reasoning as `put-on-table-schema.sql`: replaying `supabase/migrations`
-- in full would mean this suite fails whenever anything anywhere else does,
-- which is the opposite of a useful signal. What it must not do is DIVERGE, so
-- every definition below is copied from the migration that owns it.
--
-- WHAT MATTERS MOST HERE IS THE `market_calls` PRIMARY KEY. It is created in its
-- PRE-SIMULATION shape — three columns, no mode — precisely so the 20260909
-- migration has to perform the same ALTER it will perform in production. A
-- helper that pre-created the four-column key would test a migration that never
-- ran.

CREATE TABLE public.challenges (
  id                bigserial   PRIMARY KEY,
  challenger_wallet text        NOT NULL,
  market_id         bigint      NOT NULL,
  slot_no           smallint    NOT NULL CHECK (slot_no BETWEEN 1 AND 3),
  created_at        timestamptz NOT NULL DEFAULT now(),
  closed_at         timestamptz,
  close_reason      text        CHECK (close_reason IN ('creator', 'all_responded')),
  parent_call       bigint
);

CREATE UNIQUE INDEX challenges_active_slot_idx
  ON public.challenges (challenger_wallet, slot_no) WHERE closed_at IS NULL;
CREATE UNIQUE INDEX challenges_active_market_idx
  ON public.challenges (challenger_wallet, market_id) WHERE closed_at IS NULL;

CREATE TABLE public.market_calls (
  market_id        bigint      NOT NULL,
  caller_wallet    text        NOT NULL,
  responder_wallet text        NOT NULL,
  relation_at_call text        NOT NULL,
  called_at        timestamptz NOT NULL DEFAULT now(),
  responded_at     timestamptz,
  passed_at        timestamptz,
  challenge_id     bigint      REFERENCES public.challenges(id),
  id               bigint      GENERATED BY DEFAULT AS IDENTITY,
  responded_side   text        CHECK (responded_side IS NULL OR responded_side IN ('YES', 'NO')),
  PRIMARY KEY (market_id, caller_wallet, responder_wallet),
  CONSTRAINT market_calls_not_self CHECK (caller_wallet <> responder_wallet),
  CONSTRAINT market_calls_relation CHECK (
    relation_at_call IN ('twin', 'tribe', 'opp', 'inverse', 'neutral', 'insufficient')
  )
);

CREATE UNIQUE INDEX market_calls_id_idx ON public.market_calls (id);

ALTER TABLE public.challenges
  ADD CONSTRAINT challenges_parent_call_fkey
  FOREIGN KEY (parent_call) REFERENCES public.market_calls (id);

-- The two belief tables `simulation_conviction_count` folds over.
CREATE TABLE public.wallet_beliefs (
  wallet                text   NOT NULL,
  onchain_id            bigint NOT NULL,
  stance_side           text,
  last_directional_side text,
  conviction            numeric,
  PRIMARY KEY (wallet, onchain_id)
);

CREATE TABLE public.expressed_beliefs (
  wallet     text        NOT NULL,
  onchain_id bigint      NOT NULL,
  side       text        NOT NULL CHECK (side IN ('YES','NO')),
  weight     numeric     NOT NULL DEFAULT 0.15,
  source     text        NOT NULL DEFAULT 'tap',
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (wallet, onchain_id)
);

-- The recompute queue the belief write enqueues into, and its entry point.
CREATE TABLE public.match_queue (
  wallet      text PRIMARY KEY,
  enqueued_at timestamptz NOT NULL DEFAULT now(),
  pending     boolean     NOT NULL DEFAULT true
);

CREATE OR REPLACE FUNCTION public.request_viewer_match_refresh(p_wallet text)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  INSERT INTO public.match_queue (wallet, enqueued_at, pending)
  VALUES (lower(p_wallet), now(), true)
  ON CONFLICT (wallet) DO UPDATE SET pending = true, enqueued_at = now();
$$;
