/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MarketIdRouteImport } from './routes/market.$id'
import { Route as WalletAddrRouteImport } from './routes/wallet.$addr'
import { Route as ApiPublicBuildIdRouteImport } from './routes/api/public/build-id'
import { Route as ApiPublicJobsBeliefRollupRouteImport } from './routes/api/public/jobs/belief-rollup'
import { Route as ApiPublicJobsChainPollerRouteImport } from './routes/api/public/jobs/chain-poller'
import { Route as ApiPublicJobsDnaMatcherRouteImport } from './routes/api/public/jobs/dna-matcher'
import { Route as ApiPublicJobsMatchWorkerRouteImport } from './routes/api/public/jobs/match-worker'
import { Route as ApiPublicJobsPovPollerRouteImport } from './routes/api/public/jobs/pov-poller'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIdRoute = MarketIdRouteImport.update({
  id: '/market/$id',
  path: '/market/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletAddrRoute = WalletAddrRouteImport.update({
  id: '/wallet/$addr',
  path: '/wallet/$addr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBuildIdRoute = ApiPublicBuildIdRouteImport.update({
  id: '/api/public/build-id',
  path: '/api/public/build-id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsBeliefRollupRoute =
  ApiPublicJobsBeliefRollupRouteImport.update({
    id: '/api/public/jobs/belief-rollup',
    path: '/api/public/jobs/belief-rollup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsChainPollerRoute =
  ApiPublicJobsChainPollerRouteImport.update({
    id: '/api/public/jobs/chain-poller',
    path: '/api/public/jobs/chain-poller',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsDnaMatcherRoute = ApiPublicJobsDnaMatcherRouteImport.update({
  id: '/api/public/jobs/dna-matcher',
  path: '/api/public/jobs/dna-matcher',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsMatchWorkerRoute =
  ApiPublicJobsMatchWorkerRouteImport.update({
    id: '/api/public/jobs/match-worker',
    path: '/api/public/jobs/match-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsPovPollerRoute = ApiPublicJobsPovPollerRouteImport.update({
  id: '/api/public/jobs/pov-poller',
  path: '/api/public/jobs/pov-poller',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/market/$id': typeof MarketIdRoute
  '/wallet/$addr': typeof WalletAddrRoute
  '/api/public/build-id': typeof ApiPublicBuildIdRoute
  '/api/public/jobs/belief-rollup': typeof ApiPublicJobsBeliefRollupRoute
  '/api/public/jobs/chain-poller': typeof ApiPublicJobsChainPollerRoute
  '/api/public/jobs/dna-matcher': typeof ApiPublicJobsDnaMatcherRoute
  '/api/public/jobs/match-worker': typeof ApiPublicJobsMatchWorkerRoute
  '/api/public/jobs/pov-poller': typeof ApiPublicJobsPovPollerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/market/$id': typeof MarketIdRoute
  '/wallet/$addr': typeof WalletAddrRoute
  '/api/public/build-id': typeof ApiPublicBuildIdRoute
  '/api/public/jobs/belief-rollup': typeof ApiPublicJobsBeliefRollupRoute
  '/api/public/jobs/chain-poller': typeof ApiPublicJobsChainPollerRoute
  '/api/public/jobs/dna-matcher': typeof ApiPublicJobsDnaMatcherRoute
  '/api/public/jobs/match-worker': typeof ApiPublicJobsMatchWorkerRoute
  '/api/public/jobs/pov-poller': typeof ApiPublicJobsPovPollerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/market/$id': typeof MarketIdRoute
  '/wallet/$addr': typeof WalletAddrRoute
  '/api/public/build-id': typeof ApiPublicBuildIdRoute
  '/api/public/jobs/belief-rollup': typeof ApiPublicJobsBeliefRollupRoute
  '/api/public/jobs/chain-poller': typeof ApiPublicJobsChainPollerRoute
  '/api/public/jobs/dna-matcher': typeof ApiPublicJobsDnaMatcherRoute
  '/api/public/jobs/match-worker': typeof ApiPublicJobsMatchWorkerRoute
  '/api/public/jobs/pov-poller': typeof ApiPublicJobsPovPollerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/market/$id'
    | '/wallet/$addr'
    | '/api/public/build-id'
    | '/api/public/jobs/belief-rollup'
    | '/api/public/jobs/chain-poller'
    | '/api/public/jobs/dna-matcher'
    | '/api/public/jobs/match-worker'
    | '/api/public/jobs/pov-poller'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/market/$id'
    | '/wallet/$addr'
    | '/api/public/build-id'
    | '/api/public/jobs/belief-rollup'
    | '/api/public/jobs/chain-poller'
    | '/api/public/jobs/dna-matcher'
    | '/api/public/jobs/match-worker'
    | '/api/public/jobs/pov-poller'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/market/$id'
    | '/wallet/$addr'
    | '/api/public/build-id'
    | '/api/public/jobs/belief-rollup'
    | '/api/public/jobs/chain-poller'
    | '/api/public/jobs/dna-matcher'
    | '/api/public/jobs/match-worker'
    | '/api/public/jobs/pov-poller'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  MarketIdRoute: typeof MarketIdRoute
  WalletAddrRoute: typeof WalletAddrRoute
  ApiPublicBuildIdRoute: typeof ApiPublicBuildIdRoute
  ApiPublicJobsBeliefRollupRoute: typeof ApiPublicJobsBeliefRollupRoute
  ApiPublicJobsChainPollerRoute: typeof ApiPublicJobsChainPollerRoute
  ApiPublicJobsDnaMatcherRoute: typeof ApiPublicJobsDnaMatcherRoute
  ApiPublicJobsMatchWorkerRoute: typeof ApiPublicJobsMatchWorkerRoute
  ApiPublicJobsPovPollerRoute: typeof ApiPublicJobsPovPollerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$id': {
      id: '/market/$id'
      path: '/market/$id'
      fullPath: '/market/$id'
      preLoaderRoute: typeof MarketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/$addr': {
      id: '/wallet/$addr'
      path: '/wallet/$addr'
      fullPath: '/wallet/$addr'
      preLoaderRoute: typeof WalletAddrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/build-id': {
      id: '/api/public/build-id'
      path: '/api/public/build-id'
      fullPath: '/api/public/build-id'
      preLoaderRoute: typeof ApiPublicBuildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/belief-rollup': {
      id: '/api/public/jobs/belief-rollup'
      path: '/api/public/jobs/belief-rollup'
      fullPath: '/api/public/jobs/belief-rollup'
      preLoaderRoute: typeof ApiPublicJobsBeliefRollupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/chain-poller': {
      id: '/api/public/jobs/chain-poller'
      path: '/api/public/jobs/chain-poller'
      fullPath: '/api/public/jobs/chain-poller'
      preLoaderRoute: typeof ApiPublicJobsChainPollerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/dna-matcher': {
      id: '/api/public/jobs/dna-matcher'
      path: '/api/public/jobs/dna-matcher'
      fullPath: '/api/public/jobs/dna-matcher'
      preLoaderRoute: typeof ApiPublicJobsDnaMatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/match-worker': {
      id: '/api/public/jobs/match-worker'
      path: '/api/public/jobs/match-worker'
      fullPath: '/api/public/jobs/match-worker'
      preLoaderRoute: typeof ApiPublicJobsMatchWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/pov-poller': {
      id: '/api/public/jobs/pov-poller'
      path: '/api/public/jobs/pov-poller'
      fullPath: '/api/public/jobs/pov-poller'
      preLoaderRoute: typeof ApiPublicJobsPovPollerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  MarketIdRoute: MarketIdRoute,
  WalletAddrRoute: WalletAddrRoute,
  ApiPublicBuildIdRoute: ApiPublicBuildIdRoute,
  ApiPublicJobsBeliefRollupRoute: ApiPublicJobsBeliefRollupRoute,
  ApiPublicJobsChainPollerRoute: ApiPublicJobsChainPollerRoute,
  ApiPublicJobsDnaMatcherRoute: ApiPublicJobsDnaMatcherRoute,
  ApiPublicJobsMatchWorkerRoute: ApiPublicJobsMatchWorkerRoute,
  ApiPublicJobsPovPollerRoute: ApiPublicJobsPovPollerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
