/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValueRouteImport } from './routes/value'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Lab9f3c7a21b4RouteImport } from './routes/lab-9f3c7a21b4'
import { Route as HowRouteImport } from './routes/how'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MMidRouteImport } from './routes/m.$mid'
import { Route as DevVoiceRouteImport } from './routes/dev.voice'
import { Route as DevTransitionsRouteImport } from './routes/dev.transitions'
import { Route as DevRailRouteImport } from './routes/dev.rail'
import { Route as OgMarketMidRouteImport } from './routes/og/market.$mid'
import { Route as ApiPublicHomeSnapshotRouteImport } from './routes/api/public/home-snapshot'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicBuildIdRouteImport } from './routes/api/public/build-id'
import { Route as ApiPublicJobsTapeWarmRouteImport } from './routes/api/public/jobs/tape-warm'
import { Route as ApiPublicJobsSuggestionGeneratorRouteImport } from './routes/api/public/jobs/suggestion-generator'
import { Route as ApiPublicJobsPovPollerRouteImport } from './routes/api/public/jobs/pov-poller'
import { Route as ApiPublicJobsPositionReconcileRouteImport } from './routes/api/public/jobs/position-reconcile'
import { Route as ApiPublicJobsPositionRebuilderRouteImport } from './routes/api/public/jobs/position-rebuilder'
import { Route as ApiPublicJobsMatchWorkerRouteImport } from './routes/api/public/jobs/match-worker'
import { Route as ApiPublicJobsMarketRefresherRouteImport } from './routes/api/public/jobs/market-refresher'
import { Route as ApiPublicJobsMarketAnalyzerRouteImport } from './routes/api/public/jobs/market-analyzer'
import { Route as ApiPublicJobsChainPollerRouteImport } from './routes/api/public/jobs/chain-poller'
import { Route as ApiPublicJobsBeliefRollupRouteImport } from './routes/api/public/jobs/belief-rollup'

const ValueRoute = ValueRouteImport.update({
  id: '/value',
  path: '/value',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Lab9f3c7a21b4Route = Lab9f3c7a21b4RouteImport.update({
  id: '/lab-9f3c7a21b4',
  path: '/lab-9f3c7a21b4',
  getParentRoute: () => rootRouteImport,
} as any)
const HowRoute = HowRouteImport.update({
  id: '/how',
  path: '/how',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MMidRoute = MMidRouteImport.update({
  id: '/m/$mid',
  path: '/m/$mid',
  getParentRoute: () => rootRouteImport,
} as any)
const DevVoiceRoute = DevVoiceRouteImport.update({
  id: '/dev/voice',
  path: '/dev/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const DevTransitionsRoute = DevTransitionsRouteImport.update({
  id: '/dev/transitions',
  path: '/dev/transitions',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRailRoute = DevRailRouteImport.update({
  id: '/dev/rail',
  path: '/dev/rail',
  getParentRoute: () => rootRouteImport,
} as any)
const OgMarketMidRoute = OgMarketMidRouteImport.update({
  id: '/og/market/$mid',
  path: '/og/market/$mid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHomeSnapshotRoute = ApiPublicHomeSnapshotRouteImport.update({
  id: '/api/public/home-snapshot',
  path: '/api/public/home-snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBuildIdRoute = ApiPublicBuildIdRouteImport.update({
  id: '/api/public/build-id',
  path: '/api/public/build-id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsTapeWarmRoute = ApiPublicJobsTapeWarmRouteImport.update({
  id: '/api/public/jobs/tape-warm',
  path: '/api/public/jobs/tape-warm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsSuggestionGeneratorRoute =
  ApiPublicJobsSuggestionGeneratorRouteImport.update({
    id: '/api/public/jobs/suggestion-generator',
    path: '/api/public/jobs/suggestion-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsPovPollerRoute = ApiPublicJobsPovPollerRouteImport.update({
  id: '/api/public/jobs/pov-poller',
  path: '/api/public/jobs/pov-poller',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsPositionReconcileRoute =
  ApiPublicJobsPositionReconcileRouteImport.update({
    id: '/api/public/jobs/position-reconcile',
    path: '/api/public/jobs/position-reconcile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsPositionRebuilderRoute =
  ApiPublicJobsPositionRebuilderRouteImport.update({
    id: '/api/public/jobs/position-rebuilder',
    path: '/api/public/jobs/position-rebuilder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsMatchWorkerRoute =
  ApiPublicJobsMatchWorkerRouteImport.update({
    id: '/api/public/jobs/match-worker',
    path: '/api/public/jobs/match-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsMarketRefresherRoute =
  ApiPublicJobsMarketRefresherRouteImport.update({
    id: '/api/public/jobs/market-refresher',
    path: '/api/public/jobs/market-refresher',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsMarketAnalyzerRoute =
  ApiPublicJobsMarketAnalyzerRouteImport.update({
    id: '/api/public/jobs/market-analyzer',
    path: '/api/public/jobs/market-analyzer',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsChainPollerRoute =
  ApiPublicJobsChainPollerRouteImport.update({
    id: '/api/public/jobs/chain-poller',
    path: '/api/public/jobs/chain-poller',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsBeliefRollupRoute =
  ApiPublicJobsBeliefRollupRouteImport.update({
    id: '/api/public/jobs/belief-rollup',
    path: '/api/public/jobs/belief-rollup',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/how': typeof HowRoute
  '/lab-9f3c7a21b4': typeof Lab9f3c7a21b4Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/value': typeof ValueRoute
  '/dev/rail': typeof DevRailRoute
  '/dev/transitions': typeof DevTransitionsRoute
  '/dev/voice': typeof DevVoiceRoute
  '/m/$mid': typeof MMidRoute
  '/api/public/build-id': typeof ApiPublicBuildIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/home-snapshot': typeof ApiPublicHomeSnapshotRoute
  '/og/market/$mid': typeof OgMarketMidRoute
  '/api/public/jobs/belief-rollup': typeof ApiPublicJobsBeliefRollupRoute
  '/api/public/jobs/chain-poller': typeof ApiPublicJobsChainPollerRoute
  '/api/public/jobs/market-analyzer': typeof ApiPublicJobsMarketAnalyzerRoute
  '/api/public/jobs/market-refresher': typeof ApiPublicJobsMarketRefresherRoute
  '/api/public/jobs/match-worker': typeof ApiPublicJobsMatchWorkerRoute
  '/api/public/jobs/position-rebuilder': typeof ApiPublicJobsPositionRebuilderRoute
  '/api/public/jobs/position-reconcile': typeof ApiPublicJobsPositionReconcileRoute
  '/api/public/jobs/pov-poller': typeof ApiPublicJobsPovPollerRoute
  '/api/public/jobs/suggestion-generator': typeof ApiPublicJobsSuggestionGeneratorRoute
  '/api/public/jobs/tape-warm': typeof ApiPublicJobsTapeWarmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/how': typeof HowRoute
  '/lab-9f3c7a21b4': typeof Lab9f3c7a21b4Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/value': typeof ValueRoute
  '/dev/rail': typeof DevRailRoute
  '/dev/transitions': typeof DevTransitionsRoute
  '/dev/voice': typeof DevVoiceRoute
  '/m/$mid': typeof MMidRoute
  '/api/public/build-id': typeof ApiPublicBuildIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/home-snapshot': typeof ApiPublicHomeSnapshotRoute
  '/og/market/$mid': typeof OgMarketMidRoute
  '/api/public/jobs/belief-rollup': typeof ApiPublicJobsBeliefRollupRoute
  '/api/public/jobs/chain-poller': typeof ApiPublicJobsChainPollerRoute
  '/api/public/jobs/market-analyzer': typeof ApiPublicJobsMarketAnalyzerRoute
  '/api/public/jobs/market-refresher': typeof ApiPublicJobsMarketRefresherRoute
  '/api/public/jobs/match-worker': typeof ApiPublicJobsMatchWorkerRoute
  '/api/public/jobs/position-rebuilder': typeof ApiPublicJobsPositionRebuilderRoute
  '/api/public/jobs/position-reconcile': typeof ApiPublicJobsPositionReconcileRoute
  '/api/public/jobs/pov-poller': typeof ApiPublicJobsPovPollerRoute
  '/api/public/jobs/suggestion-generator': typeof ApiPublicJobsSuggestionGeneratorRoute
  '/api/public/jobs/tape-warm': typeof ApiPublicJobsTapeWarmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/how': typeof HowRoute
  '/lab-9f3c7a21b4': typeof Lab9f3c7a21b4Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/value': typeof ValueRoute
  '/dev/rail': typeof DevRailRoute
  '/dev/transitions': typeof DevTransitionsRoute
  '/dev/voice': typeof DevVoiceRoute
  '/m/$mid': typeof MMidRoute
  '/api/public/build-id': typeof ApiPublicBuildIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/home-snapshot': typeof ApiPublicHomeSnapshotRoute
  '/og/market/$mid': typeof OgMarketMidRoute
  '/api/public/jobs/belief-rollup': typeof ApiPublicJobsBeliefRollupRoute
  '/api/public/jobs/chain-poller': typeof ApiPublicJobsChainPollerRoute
  '/api/public/jobs/market-analyzer': typeof ApiPublicJobsMarketAnalyzerRoute
  '/api/public/jobs/market-refresher': typeof ApiPublicJobsMarketRefresherRoute
  '/api/public/jobs/match-worker': typeof ApiPublicJobsMatchWorkerRoute
  '/api/public/jobs/position-rebuilder': typeof ApiPublicJobsPositionRebuilderRoute
  '/api/public/jobs/position-reconcile': typeof ApiPublicJobsPositionReconcileRoute
  '/api/public/jobs/pov-poller': typeof ApiPublicJobsPovPollerRoute
  '/api/public/jobs/suggestion-generator': typeof ApiPublicJobsSuggestionGeneratorRoute
  '/api/public/jobs/tape-warm': typeof ApiPublicJobsTapeWarmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/how'
    | '/lab-9f3c7a21b4'
    | '/sitemap.xml'
    | '/terms'
    | '/value'
    | '/dev/rail'
    | '/dev/transitions'
    | '/dev/voice'
    | '/m/$mid'
    | '/api/public/build-id'
    | '/api/public/health'
    | '/api/public/home-snapshot'
    | '/og/market/$mid'
    | '/api/public/jobs/belief-rollup'
    | '/api/public/jobs/chain-poller'
    | '/api/public/jobs/market-analyzer'
    | '/api/public/jobs/market-refresher'
    | '/api/public/jobs/match-worker'
    | '/api/public/jobs/position-rebuilder'
    | '/api/public/jobs/position-reconcile'
    | '/api/public/jobs/pov-poller'
    | '/api/public/jobs/suggestion-generator'
    | '/api/public/jobs/tape-warm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/how'
    | '/lab-9f3c7a21b4'
    | '/sitemap.xml'
    | '/terms'
    | '/value'
    | '/dev/rail'
    | '/dev/transitions'
    | '/dev/voice'
    | '/m/$mid'
    | '/api/public/build-id'
    | '/api/public/health'
    | '/api/public/home-snapshot'
    | '/og/market/$mid'
    | '/api/public/jobs/belief-rollup'
    | '/api/public/jobs/chain-poller'
    | '/api/public/jobs/market-analyzer'
    | '/api/public/jobs/market-refresher'
    | '/api/public/jobs/match-worker'
    | '/api/public/jobs/position-rebuilder'
    | '/api/public/jobs/position-reconcile'
    | '/api/public/jobs/pov-poller'
    | '/api/public/jobs/suggestion-generator'
    | '/api/public/jobs/tape-warm'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/how'
    | '/lab-9f3c7a21b4'
    | '/sitemap.xml'
    | '/terms'
    | '/value'
    | '/dev/rail'
    | '/dev/transitions'
    | '/dev/voice'
    | '/m/$mid'
    | '/api/public/build-id'
    | '/api/public/health'
    | '/api/public/home-snapshot'
    | '/og/market/$mid'
    | '/api/public/jobs/belief-rollup'
    | '/api/public/jobs/chain-poller'
    | '/api/public/jobs/market-analyzer'
    | '/api/public/jobs/market-refresher'
    | '/api/public/jobs/match-worker'
    | '/api/public/jobs/position-rebuilder'
    | '/api/public/jobs/position-reconcile'
    | '/api/public/jobs/pov-poller'
    | '/api/public/jobs/suggestion-generator'
    | '/api/public/jobs/tape-warm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  HowRoute: typeof HowRoute
  Lab9f3c7a21b4Route: typeof Lab9f3c7a21b4Route
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ValueRoute: typeof ValueRoute
  DevRailRoute: typeof DevRailRoute
  DevTransitionsRoute: typeof DevTransitionsRoute
  DevVoiceRoute: typeof DevVoiceRoute
  MMidRoute: typeof MMidRoute
  ApiPublicBuildIdRoute: typeof ApiPublicBuildIdRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicHomeSnapshotRoute: typeof ApiPublicHomeSnapshotRoute
  OgMarketMidRoute: typeof OgMarketMidRoute
  ApiPublicJobsBeliefRollupRoute: typeof ApiPublicJobsBeliefRollupRoute
  ApiPublicJobsChainPollerRoute: typeof ApiPublicJobsChainPollerRoute
  ApiPublicJobsMarketAnalyzerRoute: typeof ApiPublicJobsMarketAnalyzerRoute
  ApiPublicJobsMarketRefresherRoute: typeof ApiPublicJobsMarketRefresherRoute
  ApiPublicJobsMatchWorkerRoute: typeof ApiPublicJobsMatchWorkerRoute
  ApiPublicJobsPositionRebuilderRoute: typeof ApiPublicJobsPositionRebuilderRoute
  ApiPublicJobsPositionReconcileRoute: typeof ApiPublicJobsPositionReconcileRoute
  ApiPublicJobsPovPollerRoute: typeof ApiPublicJobsPovPollerRoute
  ApiPublicJobsSuggestionGeneratorRoute: typeof ApiPublicJobsSuggestionGeneratorRoute
  ApiPublicJobsTapeWarmRoute: typeof ApiPublicJobsTapeWarmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/value': {
      id: '/value'
      path: '/value'
      fullPath: '/value'
      preLoaderRoute: typeof ValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-9f3c7a21b4': {
      id: '/lab-9f3c7a21b4'
      path: '/lab-9f3c7a21b4'
      fullPath: '/lab-9f3c7a21b4'
      preLoaderRoute: typeof Lab9f3c7a21b4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how': {
      id: '/how'
      path: '/how'
      fullPath: '/how'
      preLoaderRoute: typeof HowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$mid': {
      id: '/m/$mid'
      path: '/m/$mid'
      fullPath: '/m/$mid'
      preLoaderRoute: typeof MMidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/voice': {
      id: '/dev/voice'
      path: '/dev/voice'
      fullPath: '/dev/voice'
      preLoaderRoute: typeof DevVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/transitions': {
      id: '/dev/transitions'
      path: '/dev/transitions'
      fullPath: '/dev/transitions'
      preLoaderRoute: typeof DevTransitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/rail': {
      id: '/dev/rail'
      path: '/dev/rail'
      fullPath: '/dev/rail'
      preLoaderRoute: typeof DevRailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/market/$mid': {
      id: '/og/market/$mid'
      path: '/og/market/$mid'
      fullPath: '/og/market/$mid'
      preLoaderRoute: typeof OgMarketMidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/home-snapshot': {
      id: '/api/public/home-snapshot'
      path: '/api/public/home-snapshot'
      fullPath: '/api/public/home-snapshot'
      preLoaderRoute: typeof ApiPublicHomeSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/build-id': {
      id: '/api/public/build-id'
      path: '/api/public/build-id'
      fullPath: '/api/public/build-id'
      preLoaderRoute: typeof ApiPublicBuildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/tape-warm': {
      id: '/api/public/jobs/tape-warm'
      path: '/api/public/jobs/tape-warm'
      fullPath: '/api/public/jobs/tape-warm'
      preLoaderRoute: typeof ApiPublicJobsTapeWarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/suggestion-generator': {
      id: '/api/public/jobs/suggestion-generator'
      path: '/api/public/jobs/suggestion-generator'
      fullPath: '/api/public/jobs/suggestion-generator'
      preLoaderRoute: typeof ApiPublicJobsSuggestionGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/pov-poller': {
      id: '/api/public/jobs/pov-poller'
      path: '/api/public/jobs/pov-poller'
      fullPath: '/api/public/jobs/pov-poller'
      preLoaderRoute: typeof ApiPublicJobsPovPollerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/position-reconcile': {
      id: '/api/public/jobs/position-reconcile'
      path: '/api/public/jobs/position-reconcile'
      fullPath: '/api/public/jobs/position-reconcile'
      preLoaderRoute: typeof ApiPublicJobsPositionReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/position-rebuilder': {
      id: '/api/public/jobs/position-rebuilder'
      path: '/api/public/jobs/position-rebuilder'
      fullPath: '/api/public/jobs/position-rebuilder'
      preLoaderRoute: typeof ApiPublicJobsPositionRebuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/match-worker': {
      id: '/api/public/jobs/match-worker'
      path: '/api/public/jobs/match-worker'
      fullPath: '/api/public/jobs/match-worker'
      preLoaderRoute: typeof ApiPublicJobsMatchWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/market-refresher': {
      id: '/api/public/jobs/market-refresher'
      path: '/api/public/jobs/market-refresher'
      fullPath: '/api/public/jobs/market-refresher'
      preLoaderRoute: typeof ApiPublicJobsMarketRefresherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/market-analyzer': {
      id: '/api/public/jobs/market-analyzer'
      path: '/api/public/jobs/market-analyzer'
      fullPath: '/api/public/jobs/market-analyzer'
      preLoaderRoute: typeof ApiPublicJobsMarketAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/chain-poller': {
      id: '/api/public/jobs/chain-poller'
      path: '/api/public/jobs/chain-poller'
      fullPath: '/api/public/jobs/chain-poller'
      preLoaderRoute: typeof ApiPublicJobsChainPollerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/belief-rollup': {
      id: '/api/public/jobs/belief-rollup'
      path: '/api/public/jobs/belief-rollup'
      fullPath: '/api/public/jobs/belief-rollup'
      preLoaderRoute: typeof ApiPublicJobsBeliefRollupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  HowRoute: HowRoute,
  Lab9f3c7a21b4Route: Lab9f3c7a21b4Route,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ValueRoute: ValueRoute,
  DevRailRoute: DevRailRoute,
  DevTransitionsRoute: DevTransitionsRoute,
  DevVoiceRoute: DevVoiceRoute,
  MMidRoute: MMidRoute,
  ApiPublicBuildIdRoute: ApiPublicBuildIdRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicHomeSnapshotRoute: ApiPublicHomeSnapshotRoute,
  OgMarketMidRoute: OgMarketMidRoute,
  ApiPublicJobsBeliefRollupRoute: ApiPublicJobsBeliefRollupRoute,
  ApiPublicJobsChainPollerRoute: ApiPublicJobsChainPollerRoute,
  ApiPublicJobsMarketAnalyzerRoute: ApiPublicJobsMarketAnalyzerRoute,
  ApiPublicJobsMarketRefresherRoute: ApiPublicJobsMarketRefresherRoute,
  ApiPublicJobsMatchWorkerRoute: ApiPublicJobsMatchWorkerRoute,
  ApiPublicJobsPositionRebuilderRoute: ApiPublicJobsPositionRebuilderRoute,
  ApiPublicJobsPositionReconcileRoute: ApiPublicJobsPositionReconcileRoute,
  ApiPublicJobsPovPollerRoute: ApiPublicJobsPovPollerRoute,
  ApiPublicJobsSuggestionGeneratorRoute: ApiPublicJobsSuggestionGeneratorRoute,
  ApiPublicJobsTapeWarmRoute: ApiPublicJobsTapeWarmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
