/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiPublicBuildIdRouteImport } from './routes/api/public/build-id'
import { Route as ApiPublicJobsBeliefRollupRouteImport } from './routes/api/public/jobs/belief-rollup'
import { Route as ApiPublicJobsChainPollerRouteImport } from './routes/api/public/jobs/chain-poller'
import { Route as ApiPublicJobsMarketRefresherRouteImport } from './routes/api/public/jobs/market-refresher'
import { Route as ApiPublicJobsMatchWorkerRouteImport } from './routes/api/public/jobs/match-worker'
import { Route as ApiPublicJobsPositionRebuilderRouteImport } from './routes/api/public/jobs/position-rebuilder'
import { Route as ApiPublicJobsPositionReconcileRouteImport } from './routes/api/public/jobs/position-reconcile'
import { Route as ApiPublicJobsPovPollerRouteImport } from './routes/api/public/jobs/pov-poller'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBuildIdRoute = ApiPublicBuildIdRouteImport.update({
  id: '/api/public/build-id',
  path: '/api/public/build-id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsBeliefRollupRoute =
  ApiPublicJobsBeliefRollupRouteImport.update({
    id: '/api/public/jobs/belief-rollup',
    path: '/api/public/jobs/belief-rollup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsChainPollerRoute =
  ApiPublicJobsChainPollerRouteImport.update({
    id: '/api/public/jobs/chain-poller',
    path: '/api/public/jobs/chain-poller',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsMarketRefresherRoute =
  ApiPublicJobsMarketRefresherRouteImport.update({
    id: '/api/public/jobs/market-refresher',
    path: '/api/public/jobs/market-refresher',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsMatchWorkerRoute =
  ApiPublicJobsMatchWorkerRouteImport.update({
    id: '/api/public/jobs/match-worker',
    path: '/api/public/jobs/match-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsPositionRebuilderRoute =
  ApiPublicJobsPositionRebuilderRouteImport.update({
    id: '/api/public/jobs/position-rebuilder',
    path: '/api/public/jobs/position-rebuilder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsPositionReconcileRoute =
  ApiPublicJobsPositionReconcileRouteImport.update({
    id: '/api/public/jobs/position-reconcile',
    path: '/api/public/jobs/position-reconcile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsPovPollerRoute = ApiPublicJobsPovPollerRouteImport.update({
  id: '/api/public/jobs/pov-poller',
  path: '/api/public/jobs/pov-poller',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/public/build-id': typeof ApiPublicBuildIdRoute
  '/api/public/jobs/belief-rollup': typeof ApiPublicJobsBeliefRollupRoute
  '/api/public/jobs/chain-poller': typeof ApiPublicJobsChainPollerRoute
  '/api/public/jobs/market-refresher': typeof ApiPublicJobsMarketRefresherRoute
  '/api/public/jobs/match-worker': typeof ApiPublicJobsMatchWorkerRoute
  '/api/public/jobs/position-rebuilder': typeof ApiPublicJobsPositionRebuilderRoute
  '/api/public/jobs/position-reconcile': typeof ApiPublicJobsPositionReconcileRoute
  '/api/public/jobs/pov-poller': typeof ApiPublicJobsPovPollerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/public/build-id': typeof ApiPublicBuildIdRoute
  '/api/public/jobs/belief-rollup': typeof ApiPublicJobsBeliefRollupRoute
  '/api/public/jobs/chain-poller': typeof ApiPublicJobsChainPollerRoute
  '/api/public/jobs/market-refresher': typeof ApiPublicJobsMarketRefresherRoute
  '/api/public/jobs/match-worker': typeof ApiPublicJobsMatchWorkerRoute
  '/api/public/jobs/position-rebuilder': typeof ApiPublicJobsPositionRebuilderRoute
  '/api/public/jobs/position-reconcile': typeof ApiPublicJobsPositionReconcileRoute
  '/api/public/jobs/pov-poller': typeof ApiPublicJobsPovPollerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/public/build-id': typeof ApiPublicBuildIdRoute
  '/api/public/jobs/belief-rollup': typeof ApiPublicJobsBeliefRollupRoute
  '/api/public/jobs/chain-poller': typeof ApiPublicJobsChainPollerRoute
  '/api/public/jobs/market-refresher': typeof ApiPublicJobsMarketRefresherRoute
  '/api/public/jobs/match-worker': typeof ApiPublicJobsMatchWorkerRoute
  '/api/public/jobs/position-rebuilder': typeof ApiPublicJobsPositionRebuilderRoute
  '/api/public/jobs/position-reconcile': typeof ApiPublicJobsPositionReconcileRoute
  '/api/public/jobs/pov-poller': typeof ApiPublicJobsPovPollerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/terms'
    | '/api/public/build-id'
    | '/api/public/jobs/belief-rollup'
    | '/api/public/jobs/chain-poller'
    | '/api/public/jobs/market-refresher'
    | '/api/public/jobs/match-worker'
    | '/api/public/jobs/position-rebuilder'
    | '/api/public/jobs/position-reconcile'
    | '/api/public/jobs/pov-poller'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/terms'
    | '/api/public/build-id'
    | '/api/public/jobs/belief-rollup'
    | '/api/public/jobs/chain-poller'
    | '/api/public/jobs/market-refresher'
    | '/api/public/jobs/match-worker'
    | '/api/public/jobs/position-rebuilder'
    | '/api/public/jobs/position-reconcile'
    | '/api/public/jobs/pov-poller'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/terms'
    | '/api/public/build-id'
    | '/api/public/jobs/belief-rollup'
    | '/api/public/jobs/chain-poller'
    | '/api/public/jobs/market-refresher'
    | '/api/public/jobs/match-worker'
    | '/api/public/jobs/position-rebuilder'
    | '/api/public/jobs/position-reconcile'
    | '/api/public/jobs/pov-poller'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiPublicBuildIdRoute: typeof ApiPublicBuildIdRoute
  ApiPublicJobsBeliefRollupRoute: typeof ApiPublicJobsBeliefRollupRoute
  ApiPublicJobsChainPollerRoute: typeof ApiPublicJobsChainPollerRoute
  ApiPublicJobsMarketRefresherRoute: typeof ApiPublicJobsMarketRefresherRoute
  ApiPublicJobsMatchWorkerRoute: typeof ApiPublicJobsMatchWorkerRoute
  ApiPublicJobsPositionRebuilderRoute: typeof ApiPublicJobsPositionRebuilderRoute
  ApiPublicJobsPositionReconcileRoute: typeof ApiPublicJobsPositionReconcileRoute
  ApiPublicJobsPovPollerRoute: typeof ApiPublicJobsPovPollerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/build-id': {
      id: '/api/public/build-id'
      path: '/api/public/build-id'
      fullPath: '/api/public/build-id'
      preLoaderRoute: typeof ApiPublicBuildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/belief-rollup': {
      id: '/api/public/jobs/belief-rollup'
      path: '/api/public/jobs/belief-rollup'
      fullPath: '/api/public/jobs/belief-rollup'
      preLoaderRoute: typeof ApiPublicJobsBeliefRollupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/chain-poller': {
      id: '/api/public/jobs/chain-poller'
      path: '/api/public/jobs/chain-poller'
      fullPath: '/api/public/jobs/chain-poller'
      preLoaderRoute: typeof ApiPublicJobsChainPollerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/market-refresher': {
      id: '/api/public/jobs/market-refresher'
      path: '/api/public/jobs/market-refresher'
      fullPath: '/api/public/jobs/market-refresher'
      preLoaderRoute: typeof ApiPublicJobsMarketRefresherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/match-worker': {
      id: '/api/public/jobs/match-worker'
      path: '/api/public/jobs/match-worker'
      fullPath: '/api/public/jobs/match-worker'
      preLoaderRoute: typeof ApiPublicJobsMatchWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/position-rebuilder': {
      id: '/api/public/jobs/position-rebuilder'
      path: '/api/public/jobs/position-rebuilder'
      fullPath: '/api/public/jobs/position-rebuilder'
      preLoaderRoute: typeof ApiPublicJobsPositionRebuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/position-reconcile': {
      id: '/api/public/jobs/position-reconcile'
      path: '/api/public/jobs/position-reconcile'
      fullPath: '/api/public/jobs/position-reconcile'
      preLoaderRoute: typeof ApiPublicJobsPositionReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/pov-poller': {
      id: '/api/public/jobs/pov-poller'
      path: '/api/public/jobs/pov-poller'
      fullPath: '/api/public/jobs/pov-poller'
      preLoaderRoute: typeof ApiPublicJobsPovPollerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiPublicBuildIdRoute: ApiPublicBuildIdRoute,
  ApiPublicJobsBeliefRollupRoute: ApiPublicJobsBeliefRollupRoute,
  ApiPublicJobsChainPollerRoute: ApiPublicJobsChainPollerRoute,
  ApiPublicJobsMarketRefresherRoute: ApiPublicJobsMarketRefresherRoute,
  ApiPublicJobsMatchWorkerRoute: ApiPublicJobsMatchWorkerRoute,
  ApiPublicJobsPositionRebuilderRoute: ApiPublicJobsPositionRebuilderRoute,
  ApiPublicJobsPositionReconcileRoute: ApiPublicJobsPositionReconcileRoute,
  ApiPublicJobsPovPollerRoute: ApiPublicJobsPovPollerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
