-- CHALLENGE CHAIN — a Challenge does not end when somebody answers it.
--
-- The loop this exists to make possible:
--
--   Maya challenges Sundeep → Sundeep answers → Maya sees he showed up
--   → Sundeep puts the same question in front of HIS people → Casey answers
--   → Sundeep sees it → Casey carries it on.
--
-- Everything above the ancestry is already built: `challenges` is the editorial
-- act, `market_calls` is one row per recipient, and answering is already proved
-- server-side before it is stamped. Three columns are missing, and each one is
-- here because a screen cannot be honest without it.
--
-- WHAT IS DELIBERATELY NOT HERE: no chain table, no lineage table, no
-- materialised tree, no counters. A chain is a parent pointer and a walk. The
-- moment it becomes its own resource it is a second Challenge system, and the
-- one thing this feature must not do is create a second Challenge system.

-- ── 1 · A CALL NEEDS A NAME ──────────────────────────────────────────────────
--
-- `market_calls` is keyed (market_id, caller_wallet, responder_wallet). That is
-- the right uniqueness — there is no such thing as a second call from the same
-- person to the same person about the same market — but it cannot be POINTED AT.
-- A child Challenge has to say which call brought its author in, and a
-- three-column foreign key propagated into `challenges` would put the parent's
-- market and both wallets into a row that already knows its own market.
--
-- So the composite key stays exactly as it is, and a surrogate is added beside
-- it. The uniqueness is unchanged; only the addressability is new.
ALTER TABLE public.market_calls
  ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;

-- Not the primary key — the composite still is, and demoting it would drop the
-- guarantee that makes repeat calls impossible. This is only a handle.
CREATE UNIQUE INDEX IF NOT EXISTS market_calls_id_idx ON public.market_calls (id);

-- ── 2 · WHICH SIDE THEY TOOK WHEN THEY ANSWERED ──────────────────────────────
--
-- THIS COLUMN WAS REFUSED ONCE, ON PURPOSE, AND THE REVERSAL IS DELIBERATE.
--
-- `market_calls` had no side because its absence is what guaranteed that
-- Showing Up could never quietly become Showing Up And Agreeing: a Rival who
-- answers every call is the most valuable relationship this product can
-- surface, and a side in the relationship arithmetic would render that person
-- as unreliable. That reasoning is intact and this column does not touch it.
--
-- WHAT CHANGED IS THAT A SCREEN NOW NEEDS TO SAY "Casey backed NO" — a fact
-- about one moment, not about the relationship. The only other way to render it
-- is to read the responder's CURRENT stance, which rewrites itself the instant
-- they sell or flip: a card would claim somebody "went NO" in a market they
-- exited last week. That is the exact drift `relation_at_call` exists to
-- prevent, one column across.
--
-- THE LINE THAT KEEPS THE ORIGINAL DECISION ALIVE: this is PRESENTATION
-- CONTEXT, and `CallFact` — the shape the dependability ladder consumes — still
-- carries two timestamps and no side. Nothing in domain/dependability may ever
-- read this column. The test that asserts `CallFact`'s shape is what enforces it.
--
-- Null forever on every row written before today. It is not backfillable: the
-- side somebody held at a moment months ago is not recoverable from a table
-- that records where they stand now, and inventing it would be worse than the
-- silence. A card with no side simply does not print one.
ALTER TABLE public.market_calls
  ADD COLUMN IF NOT EXISTS responded_side text
  CHECK (responded_side IS NULL OR responded_side IN ('YES', 'NO'));

-- ── 3 · WHO BROUGHT THE AUTHOR OF THIS CHALLENGE IN ──────────────────────────
--
-- One nullable pointer, and it is the whole chain.
--
--   NULL         this person started it. A root.
--   set          they answered that call, then put the question up themselves.
--
-- ROOT AND DEPTH ARE DELIBERATELY NOT STORED. They are derivable by walking
-- parents, and a chain is two to four links in practice. Storing them would be
-- two more facts that can disagree with the pointer they were derived from —
-- and the first time a root is wrong, every screen quoting it is wrong together
-- and nothing says so. Denormalise later if a real read proves too slow; a
-- number that cannot be wrong is worth more than a join saved.
--
-- ON DELETE is absent because nothing here deletes: a Challenge closes, it is
-- never removed, so a parent can always be walked back to.
ALTER TABLE public.challenges
  ADD COLUMN IF NOT EXISTS parent_call bigint REFERENCES public.market_calls(id);

-- Walking DOWN a chain: every Challenge somebody's answer produced. The partial
-- predicate matters — the overwhelming majority of Challenges are roots, and an
-- index over a column that is almost always null should not carry them.
CREATE INDEX IF NOT EXISTS challenges_parent_call_idx
  ON public.challenges (parent_call)
  WHERE parent_call IS NOT NULL;

-- Reading one person's answered calls in the order they happened — the walk that
-- reconstructs a lineage, and the read behind "Maya → Sundeep → You".
CREATE INDEX IF NOT EXISTS market_calls_responder_answered_idx
  ON public.market_calls (responder_wallet, responded_at DESC)
  WHERE responded_at IS NOT NULL;